import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '../layout';
import BestSeller from '@/components/best-seller';
import TrendingMovies from '@/components/trending-movies';
import TopRatedMovies from '@/components/top-rated-movies';
import TrendingTv from '@/components/trending -tv';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>DuckDuckMovies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className="
      antialiased
      bg-black-acadia
    "
            >
                <Layout>
                    {/* Viết từng các section vào đây */}
                    <BestSeller />
                    <TrendingMovies />
                    <TopRatedMovies />
                    <TrendingTv />
                </Layout>
            </main>
        </>
    );
}
