import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '../layout';
import BestSeller from '@/components/best-seller';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>DuckDuckMovies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className="
      antialiased
      bg-gradient-to-r
      from-pink-300
      via-purple-300
      to-indigo-400
      bg-violet-zircon
    "
            >
                <Layout>
                    {/* Viết từng các section vào đây */}
                    <BestSeller />
                </Layout>
            </main>
        </>
    );
}
